### ISSUE TITLE
[Issue]: iOS 15 Beta 6 Crashing

### ISSUE THREAD

**Issue by Tibincrunch** [SparkDevNetwork/Rock.Mobile-Issues#1]
**Describe the bug**
Rock Mobile runs as expected the first time but after being closed and opened again, it crashes on the splash screen.

**Can reproduce in:**
- [x] Orange app
- [x] Blue app

**Steps to reproduce the behavior**
1. Install one of the iOS 15 beta versions
2. Open the Rock Mobile Core app (fresh from the store)
3. Fully close the app
4. Attempt to re-open the app

**Expected behavior**
The app will open without issue.

**Actual Behavior**
The app flashes for a brief moment when launched before disppearing.

**Basic Information**
- Mobile Shell Version: v2
- Last known good version: N/A
- iOS device type(s) and OS version(s) affected: iOS 15
- Android device type(s) OS version(s) affected: N/A

**Screenshots or Videos**
https://user-images.githubusercontent.com/11925098/130867803-d6ae4eaf-e341-4b01-be8e-b61fe35d65e6.mp4

**Reproduction XAML (if applicable)**

```xml
```

**Reproduction Site (if applicable)**

- App Id: 36
- App Url: https://www.rockrms.com/api
- App Key: _hidden_

**Comment by cabal95** [comment]
This was determined to be a bug in the iOS beta itself. iOS 15 beta 7 fixed the issue and beta 8 continues to still work. Closing this as it appears to not be an issue on our side.

(this bug affected a number of iOS apps in beta 5 and 6).
