### ISSUE TITLE
[Issue]: iOS emphasis/distinction for hyperlink text

### ISSUE THREAD

**Issue by TAGodfrey** [SparkDevNetwork/Rock.Mobile-Issues#11]
### Describe the Issue in Detail

When utilizing Content Channels with Structured Content, iOS does not emphasis or make a visual distinction between regular text and hyperlinks. Android tends to underline hyperlinks to make the distinction that the text is tappable.

### Can reproduce in

- [X] Orange App
- [X] Blue App

### Steps to Reproduce

1. Create a content channel utilizing Structured Content
2. Generate content within the Structured Content and set some of the text to 'Link'
3. Test that this open up appropriately within the app
4. Use the same text w/ 'Link' active and add any of the properties listed above
5. The text becomes untappable and no longer a hyperlink

### Expected Behavior

The expected behavior is that iOS either underlines or alters the color of the text to blue when a hyperlink is active and tappable.

### Actual Behavior

The text in iOS is tappable, however, there is no visual distinction that it is a link.

### Screenshots or Videos

![IMG_0244](https://github.com/SparkDevNetwork/Rock.Mobile-Issues/assets/87538565/8ac94c74-fca2-4162-a59f-445b171d8d99)

### Reproduction XAML

```xml
<Rock:Html FollowHyperlinks="True">
<![CDATA[
{{ Item.Content }}
 ]]>
</Rock:Html>
```

### Mobile Shell Version

v3.0-v4.0

### Last Known Working Version

NA

### iOS Device Type(s) and iOS Version(s)

All iOS Devices

### Android Device Type(s) and Android Version(s)

NA

**Comment by bradencohen** [comment]
Fixed in .NET MAUI (shell V6).
