### ISSUE TITLE
[Issue]: Deep Linking Path Prefix Causing Page Open Issues on Android

### ISSUE THREAD

**Issue by melissadrexler** [SparkDevNetwork/Rock.Mobile-Issues#13]
### Describe the Issue in Detail

When using an Android device, trying to open a link that starts with our Deep Link Path Prefix ("m") always tries to open in the app, even without a route defined for that exact URL. Example: my.itownchurch.com/mission-trips - even though the link is not my.itownchurch.com/m/mission-trips, Android devices try to open it in the app, and there is no page, so then they can't open that URL on their device.

### Can reproduce in

- [X] Orange App
- [ ] Blue App

### Steps to Reproduce

1. Get an Android device with a Rock app with deep linking enabled
2. Attempt to open a URL that starts with the same letter as the Deep Link Path Prefix specified in the app Deep Linking Settings either through email, text, etc. (not directly typed into a browser)

A specific example for the ITOWN Church app:
1. Download the ITOWN Church app on an Android device
2. Try to open the link my.itownchurch.com/mission-trips from an email app or note app

### Expected Behavior

If the URL does not exactly match the Deep Link Path Prefix, it should not try and open the link in the app.

### Actual Behavior

The device tries to open the app to a page that doesn't exist instead of opening the link in a browser app.

### Screenshots or Videos

Deep Linking Settings and Routes:
<img width="1440" alt="Deep Links Tab" src="https://github.com/SparkDevNetwork/Rock.Mobile-Issues/assets/94625940/da6e21ca-f59a-40fa-b5b7-7b572cccd6f4">
<img width="1401" alt="Deep Link Setup" src="https://github.com/SparkDevNetwork/Rock.Mobile-Issues/assets/94625940/be8119c2-b3f3-43b6-88f0-f6b8f49c7908">

In-App Example Using External Browser: https://drive.google.com/file/d/1Oe38gpnNVrrnFo1ZzE8o9kRJl6sbaNh0/view?usp=sharing
Open Link in Email Example: https://drive.google.com/file/d/1gaM93ACMFGN9xFe81esdDfEKnaPWPZK2/view?usp=sharing

### Reproduction XAML

```xml
N/A
```

### Mobile Shell Version

v5.0

### Last Known Working Version

None

### iOS Device Type(s) and iOS Version(s)

None

### Android Device Type(s) and Android Version(s)

Google Pixel running Android 13; many other devices reported as well

**Comment by bradencohen** [comment]
Hey Melissa! Thanks for filing a report. This bug was fixed recently (roughly two weeks ago) and requires a shell update to reflect.
