### ISSUE TITLE
[Issue]: Notes Block Standard Template

### ISSUE THREAD

**Issue by ryneld-tcc** [SparkDevNetwork/Rock.Mobile-Issues#15]
### Describe the Issue in Detail

The standard template in the notes block needs to have an Escape added to the {{note.PhotoUrl}}.

### Can reproduce in

- [X] Orange App
- [X] Blue App

### Steps to Reproduce

The block itself has to be set Use Template to Yes, I found if that is set to No I think it isn't an issue.  But otherwise the standard template gives an error.

### Expected Behavior

The block will render the content.

### Actual Behavior

The block only has a pink error for invalid character

### Screenshots or Videos

don't have one.

### Mobile Shell Version

1.6.0.0

### iOS Device Type(s) and iOS Version(s)

none

### Android Device Type(s) and Android Version(s)

Pixel 8 Pro android v14

**Comment by bradencohen** [comment]
Fixed in v16.7 with the new default template.
