### ISSUE TITLE
[Issue]: Unable to Change Profile Picture

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock.Mobile-Issues#18]
### Describe the Issue in Detail

In both the Orange and Blue Apps, you are unable to change your profile picture when logged in. The behavior is the same for both iPhone and Android.

In my testing in our instance, the `<Rock:LoginStatus />` Control does not work and neither does the `UpdatePersonProfilePhoto` Command. (I attempted adding this Command directly on a page with the same code that is defined in the documentation on [this page](https://mobiledocs.rockrms.com/essentials/block-commands/utility-commands#updatepersonprofilephoto).)

In this screenshot below, neither option (Photo Library, Camera) allow you to update the picture. I know this image is specific to iPhone, but we have an Android user experiencing the same behavior.

![IMG_1687](https://github.com/SparkDevNetwork/Rock.Mobile-Issues/assets/23226974/56172a1d-b96b-4130-97bd-ff7bb400c155)

### Can reproduce in

- [X] Orange App
- [X] Blue App

### Steps to Reproduce

While logged in, try to upload a new profile picture.

### Expected Behavior

Should be able to edit/add/change your profile picture.

### Actual Behavior

Unable to edit/add/change your profile picture.

### Screenshots or Videos

See above.

### Mobile Shell Version

1.6.0.0 (orange), 1.6.0.2 (blue)

### iOS Device Type(s) and iOS Version(s)

iPhone 15 Pro Max, iOS 17.2.1

### Android Device Type(s) and Android Version(s)

S22+, Version 14

**Comment by mikedotmundy** [comment]
Adding that this is an issue in Shell v5 also.

**Comment by bradencohen** [comment]
This is fixed in v5.1 and v6.
