### ISSUE TITLE
[Issue]: Sign Up Block Location Selection Options Not Selectable

### ISSUE THREAD

**Issue by melissadrexler** [SparkDevNetwork/Rock.Mobile-Issues#21]
### Describe the Issue in Detail

In the sign up block, the buttons to choose a location do not do anything. When tapping Dismiss, I've been added to the schedule but under No Location preference. The buttons also look odd, and there's black background that was not there before we updated from v14.2 to v15.3.

### Can reproduce in

- [X] Orange App
- [X] Blue App

### Steps to Reproduce

1. Create a group with multiple locations for the same schedule
2. Use the Sign Up block and select that group
3. Notice the options are not selectable and that dismissing the cover sheet adds the person to the No Location Preference slot

### Expected Behavior

The options would work to choose a location, and the background would not be black when it was not set for that.

### Actual Behavior

Location options are not selectable, thus adding all signups to No Location Preference, and the background is black.

### Screenshots or Videos

https://drive.google.com/file/d/1Z4HPwtvhpVIoyum9XOSPNKl-lq-KaxbK/view?usp=sharing

### Reproduction XAML

```xml
All of the XAML would be behind the scenes of the Sign Up block.
```

### Mobile Shell Version

v5 + v15.3

### Last Known Working Version

v5 + v14.2

### iOS Device Type(s) and iOS Version(s)

All

### Android Device Type(s) and Android Version(s)

All

**Comment by bradencohen** [comment]
Fixed along with https://github.com/SparkDevNetwork/Rock.Mobile-Issues/issues/20.
