### ISSUE TITLE
[Issue]: Deep Linking on Android Sometimes only Open App but Don't Navigate Correctly

### ISSUE THREAD

**Issue by melissadrexler** [SparkDevNetwork/Rock.Mobile-Issues#22]
### Describe the Issue in Detail

I noticed for Android the Deep Linking is only partly working. If I already have the app open, the deep link just opens the app to the page I was previously on. If I open the deep link before opening the app, it works as expected.

### Can reproduce in

- [ ] Orange App
- [ ] Blue App

### Steps to Reproduce

1. Open the app on an Android device and leave it on the home page
2. Open a different app with a deep link and tap it
3. Notice the app only opens but does not navigate to the correct page

### Expected Behavior

Regardless of if the app is currently open, tapping a deep link url should open the correct linked page.

### Actual Behavior

The deep link only opens the right page when the app was closed before tapping.

### Screenshots or Videos

https://drive.google.com/file/d/1J5V93cd97B_VPFF-xPl4rlljzHOLjBlT/view?usp=sharing

### Mobile Shell Version

v5

### Last Known Working Version

None

### iOS Device Type(s) and iOS Version(s)

iPhone 11 running 16.6

### Android Device Type(s) and Android Version(s)

Pixel 5a running Android 11 2. Motorola running Android 12.

**Comment by stanalyst** [comment]
I can confirm that we are seeing this issue with deep-linking for Androids too ... and we have had inconsistent behavior on iphone - but cannot figure out how to reproduce it. We can consistently reproduce the issue on Android though.

That said - are there any plans to fix this for the v5 / XAML shell? Or are we stuck waiting until v6 / MAUI.

**Comment by bradencohen** [comment]
Hey Stan, after discussion we decided to keep the fix as V6 only. The startup logic changed quite a bit in MAUI -- and it would require a re-fix for XF. @stanalyst
