### ISSUE TITLE
[Issue]: Account Onboarding Block Rolls Birthday Back 1 Day

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock.Mobile-Issues#23]
### Describe the Issue in Detail

Unfortunately I have been unable to replicate this issue in either the Orange or Blue Apps. I have also not been successful in replicating this in our own app. However, there have been multiple churches who are reporting this issue. We have seen this happen to at least a dozen people recently in our environment.

The Account Onboarding block is rolling a person's birthday back 1 day. (The person's birthday is on the 17th, the block rolls them back to the 16th). For us, we have seen this _only_ be an issue when a duplicate account is created (not when the block successfully matches to an existing person.)

Links to Rocket Chat Threads:
https://chat.rockrms.com/channel/mobile?msg=7wtZTZWByyF5mH3jz
https://chat.rockrms.com/channel/mobile?msg=AhDF4ttCppsnygvaN

### Can reproduce in

- [ ] Orange App
- [ ] Blue App

### Steps to Reproduce

Unable to reproduce at this time.

### Expected Behavior

Account Onboarding block should keep the birthdate the person enters.

### Actual Behavior

Account Onboarding block will _occasionally_ roll the person's birthday back 1 day (17th to the 16th)

### Screenshots or Videos

None

### Mobile Shell Version

v6.0

### iOS Device Type(s) and iOS Version(s)

Multiple

### Android Device Type(s) and Android Version(s)

Multiple

**Comment by KarenRossi84** [comment]
I have been able to duplicate this on our database. April birthdays especially seem to be an issue. I have been tracking all of them that I personally have found in a spreadsheet. Over the course of about a month we had 53 folks. About 2/3 of those that I tracked all had an April Birthdate. Once I figured that out, I was able to trigger it to occur using an April birthdate in our database. 

I created a new person with unique telephone and email by onboarding on the app with an April birthday. I then clicked log out and proceeded to onboard again using that same telephone number. All fields from that moment on were then autofilled with the "matching" profiles information but the birthday came through automatically as one day lower. It then created a new pending person even though first name, last name, email address, mobile telephone number, birth month and birth year were all the same just the date within the month was one lower. These uniquely also did not have their telephone number and emails on others in the database. They were uniquely on the 2 profiles (the original and the one with the bday one day off.)

I was able to continue to trigger this to happen using a variety of dates within April. I am also not seeing a trend with this involving only those born in a leap year or anything like that.

**Comment by mikedotmundy** [comment]
We have seen this with people who have birthdays in other months - the most recent 2 were in February and September.

**Comment by KarenRossi84** [comment]
Here are some birthdates that have triggered it: 4/5/1984, 
4/19/1962, 4/25/1964, 5/22/1958, 10/15/1952, 4/21/1972, 4/13/1968, 4/9/1960, 10/3/1948, 6/20/1963

April, June, and October make up almost all of the 53 people in my list

**Comment by tikool17** [comment]
We're also experiencing this with varied birthdays. Creating a lot of unnecessary duplicates. Months of January, September and July from a couple that i'm able to see quickly. I wouldn't rule out timezone or time-related issues as contributing to this. We have noticed most issues on our end from one of our campuses in a different time zone.

**Comment by bradencohen** [comment]
Thanks everyone for the thorough reporting, especially @KarenRossi84 , that write-up was SUPER clear and helpful.

Made a world of difference in tracking this one down!

Fixed in v5.1 & v6.

**Comment by JimMichael** [comment]
This is awesome, but are you really gonna leave us hanging and not say what the bug was? (TL;DR version?) 🤣🤓

**Comment by bradencohen** [comment]
Haha! 

The bug was that the shell was decoding the matched person's birth date into a local date time. This caused the value to be "rolled back one day" in certain cases. 

I was able to reproduce the exact behavior @KarenRossi84 described by setting my test device to be in a time-zone very far behind the server time-zone.

@JimMichael

**Comment by tikool17** [comment]
@bradencohen thanks so much for this! i'm not as familiar with how versions work with the app. Will implementing this require a resubmit of our app? Or is it already live somehow? We're on Shell Version 1.6.0.4

**Comment by bradencohen** [comment]
@tikool17 It does require a re-submission of the app. 

The fix went out in version 1.0.71 in the blue app today, if you had a solid way to replicate the bug should not be present there.
