### ISSUE TITLE
[Issue]: Onboarding Block Does Not Respect Setting for "Hide Campus if Known"

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock.Mobile-Issues#28]
### Describe the Issue in Detail

When using the onboarding block, setting the "Hide Campus if Known" setting to "Yes" does not actually hide the campus if it is known.

### Can reproduce in

- [ ] Orange App
- [ ] Blue App

### Steps to Reproduce

1. Place the Onboarding block on any page
2. Set the "Hide Campus if Known" setting to "Yes"
3. Visit the page and use the phone number of a person whose campus is known
4. See that the onboarding block still asks for the person's campus

### Expected Behavior

The onboarding block should not ask for the person to select their campus if it is already known and the "Hide Campus if Known" setting is set to "Yes".

### Actual Behavior

The onboarding block currently still asks for the person to select their campus even if it is already known and the "Hide Campus if Known" setting is set to "Yes".

### Screenshots or Videos

n/a

### Mobile Shell Version

6.0.0.0

### iOS Device Type(s) and iOS Version(s)

iPhone 13 Pro on iOS 17.4.1

### Android Device Type(s) and Android Version(s)

n/a

**Comment by adamhann** [comment]
I'm not sure how I can verify this, but I can verify and it's a problem for both iOS 17 and Android 14.

**Comment by bradencohen** [comment]
Fixed in Rock Core v16.7.
