### ISSUE TITLE
[Issue]: Onboard Person block accepts characters which cause rock Person Profile page to throw an exception

### ISSUE THREAD

**Issue by stanalyst** [SparkDevNetwork/Rock.Mobile-Issues#33]
### Describe the Issue in Detail

If a user has a custom keyboard installed on their mobile device which allows for special fonts (like double-struck, script, etc) - and uses one of these fonts when they enter their FirstName and/or LastName in the Onboard Person block when creating their profile. The resulting profile can NOT be opened in the person profile page - and throws an exception.

### Can reproduce in

- [ ] Orange App
- [ ] Blue App

### Steps to Reproduce

1 - install a Keyboard Font app on your mobile device - and select a custom font.
2 - try to create a new profile in the Rock mobile app
3 - be sure to use a custom font when entering the first and/or last name
4 - try and view the new profile on the Person Profile page in rock.
5 - observe exception

### Expected Behavior

The Onboard Person block should NOT accept any characters or content which cause exceptions in other pages/block/etc of Rock.

### Actual Behavior

If a user enters their first or last name with a custom font when creating their profile via the mobile app - viewing that profile in Rock will cause an exception.

### Screenshots or Videos

![CustomFontExample](https://github.com/SparkDevNetwork/Rock.Mobile-Issues/assets/112125627/95640671-cbb5-473f-aaa8-d18aa603737a)

### Mobile Shell Version

1.5.0.23

### iOS Device Type(s) and iOS Version(s)

iPhone 13 Pro - 17.4.1

### Android Device Type(s) and Android Version(s)

unconfirmed

**Comment by Panha-Sim** [comment]
Hello @stanalyst, this issues is fixed in shell 7.

**Comment by stanalyst** [comment]
@Panha-Sim  Any chance of getting the fix into v6.x shell also? We're currently on v5.x and preparing for the move to v6 in January.

**Comment by bradencohen** [comment]
Hey @stanalyst, good question!

Since V6 was packaged some time ago and this issue appears to have relatively low impact, we’re opting to include the fix/feature in V7.

**Comment by adamhann** [comment]
> Hey @stanalyst, good question!
> 
> Since V6 was packaged some time ago and this issue appears to have relatively low impact, we’re opting to include the fix/feature in V7.

Any thoughts on when v7 would go live? We also have this issue. :)
