### ISSUE TITLE
[Issue]: Calendar View display issues.

### ISSUE THREAD

**Issue by trydyingtolive** [SparkDevNetwork/Rock.Mobile-Issues#34]
### Describe the Issue in Detail

The Calendar View block seems to have some display issues. I noticed this when calendars suddenly stopped displaying correctly. I was able to reproduce this on a fresh app.

The month on the calendar by default is too short so it doesn't display the text. The next and previous months also do not appear.

This is what the documentation shows
![image](https://github.com/user-attachments/assets/738c8e4d-814e-4e3b-83f4-0ec6ed9a934a)

This is what is looks like on Android (iOS is similar)
![Screenshot_20240819-144353](https://github.com/user-attachments/assets/0114e4fe-8bbc-4caf-9991-6f130a555c46)

Additionally when selecting a calendar date, the event details do not appear. 

### Can reproduce in

- [X] Orange App
- [X] Blue App

### Steps to Reproduce

Add a Calendar View block to a page.

### Expected Behavior

Visible month, next and previous months, and details when a date is selected.

### Actual Behavior

The month is not visible and when selecting a day the events for the month do not appear.

### Screenshots or Videos

![Screenshot_20240819-144353](https://github.com/user-attachments/assets/f7b5e91f-646e-4294-bec5-9b7c3b9a804e)

### Mobile Shell Version

6.0.0.0

### Last Known Working Version

v5

### iOS Device Type(s) and iOS Version(s)

iPhone 14

### Android Device Type(s) and Android Version(s)

Pixel 6, Pixel 8

**Comment by bradencohen** [comment]
Fixed in shell V6. This fix should be testable in iOS App Store Version 1.0.81 in the blue app.

**Comment by trydyingtolive** [comment]
It appears that the calendar block continues to have issues. The top most image is Android. A date with and event is selected, but it is not visible below the calendar. The second image is iOS. Both of the screenshots are from the Blue app iOS 1.0.81 and Android 1.0.80

![Screenshot_20241104-143450](https://github.com/user-attachments/assets/8ad3fc68-52ec-4636-9775-702c96dc4b43)
![IMG_0015 1](https://github.com/user-attachments/assets/7c5ef5c9-8b2d-45f1-bd42-d21e59963999)

**Comment by bradencohen** [comment]
@trydyingtolive would you mind sharing your layout? Is there a ScrollView, and if so, could you try removing it?

**Comment by trydyingtolive** [comment]
I'm just using the default homepage layout

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:Rock="clr-namespace:Rock.Mobile.Cms;assembly=Rock.Mobile"
             xmlns:Common="clr-namespace:Rock.Mobile.Common;assembly=Rock.Mobile.Common">
    <ScrollView>
        <StackLayout>
            <Rock:Zone ZoneName="Main" />
        </StackLayout>
    </ScrollView>
</ContentPage>
```

**Comment by bradencohen** [comment]
@trydyingtolive it does look like there's a ScrollView in that layout. The Calendar View (event list) uses a component with built in scrolling mechanics, meaning it can't have an outer ScrollView. 

We've documented this for some of the newer blocks with this behavior, but I'll double check the Calendar View documentation and make sure it has this mentioned.

**Comment by trydyingtolive** [comment]
I removed the scroll view in the layout and redeployed the app. Here is the layout I used.

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:Rock="clr-namespace:Rock.Mobile.Cms;assembly=Rock.Mobile"
             xmlns:Common="clr-namespace:Rock.Mobile.Common;assembly=Rock.Mobile.Common">
    
        <StackLayout>
            <Rock:Zone ZoneName="Main" />
        </StackLayout>
    
</ContentPage>
```


Here is the page
![Screenshot 2024-11-07 at 16-35-12 Pages Rock RMS](https://github.com/user-attachments/assets/4c1580b7-5801-4a95-8404-be7a6de4c56f)

Here are the settings
![image](https://github.com/user-attachments/assets/b2047276-cd9e-468a-a3d4-f1d2e999b377)

Here are the results on iOS:
![IMG_0016 1](https://github.com/user-attachments/assets/25c9613e-b967-4cc5-9b55-5305beaa454f)
