### ISSUE TITLE
[Issue]: Structured Content View Block doesn't Allow Scrolling After Saving

### ISSUE THREAD

**Issue by mshankle** [SparkDevNetwork/Rock.Mobile-Issues#4]
### Describe the Issue in Detail

Our app uses the Structured Content View block to contain message notes so that a user can go back to their sermon notes to read them after services. However, if the note text is longer than the default note entry size, the user cannot go in and scroll to see extra text. If you tap and highlight the box, you can copy and paste everything so the text is saved, just not viewable.

Screen recording attached using an iPhone 11: https://community.rockrms.com/ideas/1672/structured-content-view-block-doesn-t-allow-scrolling-after-saving

### Can reproduce in

- [X] Orange App
- [ ] Blue App

### Steps to Reproduce

1. Take notes in a Message Note content channel item, making sure the text is very long and goes past the initial entry box size
2. Leave page (after it autosaves)
3. Go to view notes again 
4. Attempt to tap into notes to scroll to bottom of entry box content
5. Screen recording attached using an iPhone 11.

### Expected Behavior

I can scroll in the text box as normal so that I can see all the text I previously entered.

### Actual Behavior

The text box is not scrollable so any text not in the default area cannot be viewed.

### Screenshots or Videos

Video: https://community.rockrms.com/ideas/1672/structured-content-view-block-doesn-t-allow-scrolling-after-saving

### Mobile Shell Version

v2.0

### iOS Device Type(s) and iOS Version(s)

All but iOS 14.8.1 on iPhone 11 tested specifically

### Android Device Type(s) and Android Version(s)

All

**Comment by cabal95** [comment]
Fixing this required a change to both Rock Server as well as the Mobile Shell. We weren't able to get the scrolling to work (surprisingly that is harder than you would think with that particular control); so instead we opted to make the text field auto-size itself to fit the text.

This fix for this will be in Mobile Shell 2.1 as well as Rock v13 (technically Rock v12.8, but I don't think we are expecting to release Rock v13 before 12.8 sees the light of day).
