### ISSUE TITLE
[Issue]: Connection Opportunity List block shows Inactive Opportunities

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock.Mobile-Issues#6]
### Describe the Issue in Detail

When using the Connection Opportunity List block on Rock Mobile, the block shows _all_ opportunities, **including inactive opportunities**. There's no way to filter them out in the UI or with a block setting. The only way to remove inactive opportunities is to wrap the `<Frame StyleClass="connection-opportunity"` with this:
```
{% if opportunity.IsActive %}
   <Frame StyleClass="connection-opportunity"
                HasShadow="false">
   [rest of <Frame ... /> code here]
{% else %}
   {% continue %}
{% endif %}
```

### Can reproduce in

- [X] Orange App
- [ ] Blue App

### Steps to Reproduce

1. On a Rock instance running v13.3 or later, navigate to People > Connections
2. Click the Options gear in the corner to view the available Connection Types
3. Click one of the Connection Types in the list
4. Note which type you clicked on
5. Click on one of the Connection Opportunities listed and make sure it is _Inactive_
6. Take note of the name of the Opportunity that is _Inactive_
7. Navigate to Admin Tools > CMS Configuration, and click `Mobile Applications`
8. Click on the app in the list that you can test with
9. Within the App's Pages configuration, add a `Mobile Connection Opportunities` page
10. To that page, add the `Connection Opportunity List` block (leave at default settings)
11. Within the App's Pages configuration, add a `Mobile Connection Types` page (_Display In Navigation_ should be checked)
12. To that page, add the `Connection Type List` block
13. In the block settings, set the `Detail Page` to the page created in step 7
14. From the main application page, click Deploy
15. On a mobile device, launch the app you're testing with and tap on the `Mobile Connection Types` page
16. Tap on the Connection Type noted in step 4
17. Notice the inactive opportunity noted in step 6 in the list

### Expected Behavior

I would expect the `Connection Opportunity List` block to only display the active connection opportunities for the given connection type.

### Actual Behavior

All connection opportunities for the given type are listed, both active and inactive.

### Screenshots or Videos

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/66277785/190833945-1c994f51-ef70-4580-815b-3944f5a4398c.png">

Mobile Connection Opportunities Page configuration:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/66277785/190833982-cc5da94f-3530-4134-b9db-08db9fec39a2.png">

Mobile Connection Types Page configuration:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/66277785/190833998-73082251-95d7-4e75-a8c9-489921cbfa2c.png">

Mobile Connection Opportunities page in mobile:
![image](https://user-images.githubusercontent.com/66277785/190834041-10ab50c9-d131-43b6-b680-1672109a78ff.png)

### Mobile Shell Version

1.3.0.14

### iOS Device Type(s) and iOS Version(s)

iPhone 14 Pro; iOS 16.0.1

### Android Device Type(s) and Android Version(s)

Haven't tested on Android

**Comment by bradencohen** [comment]
This was added as a block setting named 'Include Inactive' to the ConnectionOpportunityList block, in Rock v14.1.
