### ISSUE TITLE
[Issue]: with ScheduleSignUp block for Mobile

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock.Mobile-Issues#8]
### Describe the Issue in Detail

Sign up works fine on website:
![image](https://user-images.githubusercontent.com/657005/202336327-75b5caad-ef88-4abf-aa2e-9d2e12197293.png)

Signup does not work on mobile

![image](https://user-images.githubusercontent.com/657005/202336350-ac1f54b6-953a-48d0-9b83-10c9cfce4ccb.png)

Mobile is not looking at this box:

<img width="240" alt="thumb-Clipboard - November 16, 2022 2_23 PM" src="https://user-images.githubusercontent.com/657005/202336433-672591e7-6dd3-4bf8-ab06-1f34088eaa79.png">

### Description

When using schedule sign up on a mobile application in v14 - if an individual has not met all the group requirements they cannot sign up for a schedule. They are shown a blank screen - even if Scheduling Must Meet Requirements setting is not checked. 

### Versions

* **Rock Version:** V14
* **Client Culture Setting:** en-us

### Can reproduce in

- [ ] Orange App
- [ ] Blue App

### Steps to Reproduce

1. See images.

### Expected Behavior

When the "Schedule Must Meet Requirements" box is not checked - people who do not meet the requirements to be scheduled for the group should still be able to sign up.

### Actual Behavior

They are able to sign up on the website but not using the mobile block. 

### Screenshots or Videos

see description above.

### Mobile Shell Version

unknown

### iOS Device Type(s) and iOS Version(s)

unknown

### Android Device Type(s) and Android Version(s)

unknown

**Comment by bradencohen** [comment]
Confirmed this as a bug, the server currently filters out people who don't meet the scheduling requirements regardless of that checkbox value.

Fixed via [this commit ](https://github.com/SparkDevNetwork/Rock/commit/4c9a6a95331bdd1adba7c51c1d401a3730966d12) in v14.1, and in shell v4, there will be a friendlier message displayed rather than just a blank screen.
