### ISSUE TITLE
[Issue]: Cannot Watch Video in Landscape Mode for iOS 16

### ISSUE THREAD

**Issue by melissadrexler** [SparkDevNetwork/Rock.Mobile-Issues#9]
### Describe the Issue in Detail

The video player will not go into landscape mode for devices running iOS 16. It allows for the full screen but not landscape.

### Can reproduce in

- [X] Orange App
- [x] Blue App

### Steps to Reproduce

1. Go to a page with a video using the Rock:MediaPlayer
2. Tap the full screen button
3. Turn phone sideways to normally trigger landscape mode

### Expected Behavior

If I turn a device without a rotation lock on, the video will switch to landscape mode.

### Actual Behavior

The video stays full screen in portrait mode. 

### Screenshots or Videos

Linked are videos of the expected behavior of an [iPhone 11 on OS 15.6.1 ](https://drive.google.com/file/d/1ZynR-fugSPeToR3NxgRLcmMnCEDkhHxY/view?usp=share_link)and then an [iPhone XSMax on OS 16.1.1](https://drive.google.com/file/d/1F4JD-CzNARjZYnjoSO8-A_DxnKHXCFyk/view?usp=sharing)

### Reproduction XAML

```xml
{% assign videoId = Item | Attribute:'VideoLink' | Trim  %}
{% assign HSLLink = Item | Attribute:'HLSLink','RawValue' | Trim  %}
{% assign vidUrl = HSLLink %}

<StackLayout>
    {% if vidUrl != '' %}
        <Rock:MediaPlayer AutoPlay="False"
                {% if imgLink and imgLink != '' %}ThumbnailSource="{{ imgLink }}"{% endif %}
                PlayButtonSource="https://admin.itownchurch.com/Content/ExternalSite/Mobile/PlayButton.png"
                Source="{{ vidUrl | Escape }}"/>
    {% else %}
    {% endif %}
</StackLayout>
```

### Mobile Shell Version

v2.0 (I think)

### Last Known Working Version

Same as current shell

### iOS Device Type(s) and iOS Version(s)

OS Version 16.0+

### Android Device Type(s) and Android Version(s)

N/A

**Comment by bradencohen** [comment]
Here are some comments on this, after I was able to reproduce the issue on an iPhone 14 running iOS 16+.

You can _fix_ this behavior by setting the "Lock Portrait Orientation" application setting to blank, which translates to respective of both "Portrait" and "Landscape" mode. 
![image](https://user-images.githubusercontent.com/11482832/211682391-0f5e887c-da68-4440-8575-f6bc128c7e17.png)

With that being said, having an application confined to "Portrait" mode should not apply when you're within a fullscreen video. They recently added some things in iOS 16+ that are required to allow screen orientation changes ( [UIWindowSceneGeometryPreferences ](https://developer.apple.com/documentation/uikit/uiwindowscenegeometrypreferencesios?language=_2) ), so we'll  need to add that new logic into the control.

**Comment by bradencohen** [comment]
This is fixed in shell version 5.
